name: "API"

arch:
    type: "RandomForestClassificationModel"
    args:
        max_depth: 8
        min_samples_leaf: 8
        min_samples_split: 8
        n_estimators: 100
        

data_loader:
    type: "APIDataLoader"
    args:
        apidata_dir: "data/apidata"
        data_dir: "data/dataset/unziped"
        metadata_path: "data/train_metadata.csv"
        validation_split: 0.1
        shuffle: true
        num_workers: 2

metrics: [
    "accuracy_score", "f1_score"
]

trainer:
    verbosity: 2
    save_dir: "saved/"
    mlflow_dir: "saved/"