name: "Opcode"

arch:
    type: "SVMClassificationModel"
    args: {}

data_loader:
    type: "OpcodeDataLoader"
    args:
        data_dir: "data/dataset/unziped"
        metadata_path: "data/train_metadata.csv"
        n_gram: 2
        validation_split: 0.1
        shuffle: true
        num_workers: 2

metrics: [
    "accuracy_score", "f1_score"
]

trainer:
    verbosity: 2
    save_dir: "saved/"
    mlflow_dir: "saved/"