name: "Evaluation"

arch:
    type: [
        'runs:/9b60a26d19ef444ca652bff91ff27013/model',
        'runs:/af0e6c8412e0469c8cf66be4bd14cea6/model',
        'runs:/8570c954c4324679abecc3ebe9e91e93/model',
    ]    

data_loader:
    type: [
        "APIDataLoader",
        "OpcodeDataLoader",
        "SpecDataLoader",
    ]

metrics: [
    "accuracy_score", "f1_score"
]

    